mongo:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=localDB
      - MONGODB_APPLICATION_USER=user
      - MONGODB_APPLICATION_PASS=pass
    ports:
      - "27017:27017"
    volumes:
        - ./mongo:/data/db

